### ISSUE TITLE
need a file routing feature like express.

### ISSUE THREAD

**Issue by manaskumar-syon** [tinyhttp/tinyhttp#273]
**Is your feature request related to a problem? Please describe.**
What problem does it solve?

need a file routing feature like express.

**Describe the solution you'd like**
app.use('/',path of the file);

**Describe alternatives you've considered**

when we work on a real-time complex project then it is needed.
**Additional context**

**Comment by talentlessguy** [comment]
ummm you didn't add any references or links to file routing in express. I've never heard of that. please elaborate

**Comment by manaskumar-syon** [comment]
// Bring in our dependencies const app =require('express')(); const routes =require('./routes'); // Connect all our routes to our application app.use('/', routes); // Turn on that server! app.listen(3

**Comment by talentlessguy** [comment]
@manaskumar-syon you can already do that:

```js
import { App } from '@tinyhttp/app'
import { routes } from './routes.js'

const app = new App()

app.use(routes)

app.listen(3000)
```

**Comment by manaskumar-syon** [comment]
it is showing module not found after import 

import { App } from '@tinyhttp/app';
import { route } from './routes/route';

let app = new App();

app.use('/api',route);

app.listen(3000,() =>{
    console.log("server started at "+3000)
})


import { Router  } from '@tinyhttp/router';
const router = new Router();


router.get('/', (req, res) => res.send('Hello World'));

module.exports = router;



how to export it on route file

**Comment by talentlessguy** [comment]
@manaskumar-syon this is not a tinyhttp issue

you're misusing module paths for Node.js. they need explicit extensions. I'd recommend to read [this](https://nodejs.org/api/esm.html) to understand ESM in Node.js better.

also btw, `Router` class doesn't have req / res methods so it won't work. Use subapps instead (such as `app.use(new App())`

**Comment by manaskumar-syon** [comment]
now it is showing reference h is not defined, can you please edit the above coading and guide me for the proper way to do it.

**Comment by manaskumar-syon** [comment]
//index.js


import { App } from '@tinyhttp/app';
import { router } from './routes/route.mjs';

let app = new App();

app.use(router)

app.listen(3000,() =>{
    console.log("server started at "+3000)
})


//route.mjs
import { Router  } from '@tinyhttp/router';
const router = new Router();


router.get('/', (req, res) => res.send({msg: 'Hello World'}));

export {router};


this is my current code

**Comment by talentlessguy** [comment]
as I said, `@tinyhttp/router` doesn't contain req / res. it's just a an interface about arrays to be honest. it's not meant to be used directly. Please use `App` instead

**Comment by talentlessguy** [comment]
I recommend checking https://github.com/tinyhttp/tinyhttp/tree/master/examples/subapps

**Comment by manaskumar-syon** [comment]
thanks, it is working now.
