### ISSUE TITLE
Some router paths don't work if router is mounted after defining routes

### ISSUE THREAD

**Issue by weedz** [tinyhttp/tinyhttp#278]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/talentlessguy/tinyhttp/issues/278)

**Describe the bug**

Can not find the correct route when using sub-apps.

**To Reproduce**

The following code does not work as intended:
```javascript
import { App } from '@tinyhttp/app';

const app = new App()

const router = new App();
router.get("/list", (req,res) => {
    console.log("router/list");
    res.send("router/list");
});
router.get("/find", (req,res) => {
    console.log("router/find");
    res.send("router/find");
});
app.use("/router", router);

app.listen(3000);
```
I can't request `/router/find` but `/router/list` works.

If I instead "use" `router` before we define any routes it works:
```javascript
import { App } from '@tinyhttp/app';

const app = new App()

const router = new App();
app.use("/router", router); // <-- HERE, we "use" router before we add any routes
router.get("/list", (req,res) => {
    console.log("router/list");
    res.send("router/list");
});
router.get("/find", (req,res) => {
    console.log("router/find");
    res.send("router/find");
});

app.listen(3000);
```

**Expected behavior**

Should not matter where the `use` is called? When requesting `/router/find` you should see `router/find` instead of `Not Found`.

**Versions**

* `node`: 14.16.1
* `@tinyhttp/app`: 1.3.11

**Additional context**

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/35937217?v=4' alt='talentlessguy' width=24 height=24> talentlessguy](https://issuehunt.io/u/talentlessguy) ($5.00)

### Submitted pull Requests
- [#292 Fix router mount order (fixes #278)](https://issuehunt.io/r/talentlessguy/tinyhttp/pull/292)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/talentlessguy/tinyhttp/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by weedz** [comment]
This might not be the correct way to solve this (and might possibly break other things?) but in the `App.use` function, if we map over all the middlewares instead of only the first one it seems to work.
```diff
pushMiddleware(this.middleware)({
  path: base as string,
  regex,
  type: 'mw',
  handler: mount(fns[0] as Handler),
  handlers: fns.slice(1).map(mount),
  fullPaths: fns
  .flat()
  .map((fn) =>
-    fn instanceof App && fn.middleware?.[0] ? lead(base as string) + lead(fn.middleware?.[0].path)  : ''
+    fn instanceof App && fn.middleware?.length ? fn.middleware.map(mv => lead(base as string) + lead(mv.path))  : ''
  )
})
```

**Comment by talentlessguy** [comment]
@weedz could you please fork it and check on some unit tests for router?

**Comment by weedz** [comment]
> @weedz could you please fork it and check on some unit tests for router?

Sure

**Comment by weedz** [comment]
Does not seem to work. Fails at 
> Testing App routing › should can set url prefix for the application

Returns "Not Found" for /abc/route2 and /abc/route3
