### ISSUE TITLE
Support port numbers as strings (maybe?)

### ISSUE THREAD

**Issue by fabiospampinato** [tinyhttp/tinyhttp#285]
**Is your feature request related to a problem? Please describe.**

I'd like to write the cleanest code possible, and I think it's pretty common to want to write something like this:

```ts
app.listen ( process.env.APP_PORT );
```

The thing is that process.env.* variables are always strings, so I need to wrap that in `Number`:

```ts
app.listen ( Number ( process.env.APP_PORT ) );
```

**Describe the solution you'd like**

Maybe `app.listen` should accept a string for a port too just for this use case? Like it obviously should be a number ideally, but maybe accepting strings for making this cleaner and more express-compatible is worth it?

**Describe alternatives you've considered**

Wrapping those env variables in `Number`.

**Comment by fabiospampinato** [comment]
It seems that a port as a string works just the same, in some sense the types are kind of wrong then 🤔 I think it'd like to see this minor thing changed.

**Comment by talentlessguy** [comment]
imo it's not quite safe to allow ports to be passed as strings because someone can do this:

```ts
app.listen('bruh')
```

which is not good

proper way to load port from env is to do this: `app.listen(parseInt(process.env.PORT, 10))`

**Comment by fabiospampinato** [comment]
That's too noisy IMO, I think it's ok to throw if the thing passed to it once piped to parseInt doesn't returning a number > 0.

But I'm ok with this being a number too, the resulting code is just a bit less clean.
