### ISSUE TITLE
Ensure there are defaults noMatchHandler and onError functions

### ISSUE THREAD

**Issue by fabiospampinato** [tinyhttp/tinyhttp#288]
**Describe the bug**

It seems that if an error is thrown inside a route handler the app just hangs, so it seems there's at least no default `onError` handler. IMO a default one should be provided.

**To Reproduce**

Just throw inside a route.

**Expected behavior**

Default handlers provided.

**Versions**

- `node`: 12.12.0
- `@tinyhttp/app`: latest

**Comment by talentlessguy** [comment]
not sure what you're talking about

it sets defaults here:

https://github.com/tinyhttp/tinyhttp/blob/08cff9e507ad8f4496a1181ea5e2b9d4baf50993/packages/app/src/app.ts#L106-L107

there's even a test for `throw`ing inside routes:

https://github.com/tinyhttp/tinyhttp/blob/08cff9e507ad8f4496a1181ea5e2b9d4baf50993/tests/core/app.test.ts#L216-L226

**Comment by fabiospampinato** [comment]
I'll try to make a repro tomorrow. I've just experienced a route handler throwing and the browser just waiting endlessly for the response 🤷

**Comment by fabiospampinato** [comment]
I can't reproduce it anymore. If I'll happen to see that again I'll make sure to make a repro.
