### ISSUE TITLE
req.path computed improperly

### ISSUE THREAD

**Issue by fabiospampinato** [tinyhttp/tinyhttp#290]
**Describe the bug**

For a route like this:

```ts
app.get ( '/:format?/:uml?', async ( req, res ) => {} );
```

Queried like this:

```
http://localhost:3000/svg/SyfFKj2rKt3CoKnELR1Io4ZDoSdd0W00
```

I'm getting the following path inside the route handler:

```ts
'/SyfFKj2rKt3CoKnELR1Io4ZDoSdd0W00'
```

Which isn't correct, it should instead be:

```
'/svg/SyfFKj2rKt3CoKnELR1Io4ZDoSdd0W00'
```

**Comment by talentlessguy** [comment]
probably that line to support subapps mounting on routes breaks the rest of routes ... I need to come up with a better solution
