### ISSUE TITLE
`res.sendFile` method forcibly overwrites the HTTP status code with 200

### ISSUE THREAD

**Issue by e965** [tinyhttp/tinyhttp#294]
**To Reproduce**

```ts
app.use((req, res) => {
    res.status(404);
    res.sendFile(join(staticPath, '404.html'));
});
```

**Versions**

- `node`: 16.4.1
- `@tinyhttp/app`: 1.3.14

**Additional context**

Не хочу, чтобы мой корявый английский испортил контекст, поэтому напишу здесь на русском (прошу прощения у автора заранее): я в своём приложении собираюсь сделать страницу по умолчанию для всех не прописанных заранее путей (страница 404, короче). Если просто делаю `res.status(404).end()`, то всё ок, но когда пытаюсь в нагрузку ещё и HTML-файл отправить - код перезаписывается на 200.

Покопался в исходниках и даже кажется нашёл, [где есть](https://github.com/tinyhttp/tinyhttp/blob/072e75fea7eed2ff341c2b5ca25d8410c8762e7f/packages/send/src/sendFile.ts#L102) проблема. В принципе, понимаю, зачем это было сделано, но в моём случае это неправильное поведение со стороны сервера, и было бы круто поправить :)

Regards!

**Comment by talentlessguy** [comment]
should be fixed in `@tinyhttp/app@1.3.15`
