### ISSUE TITLE
Replace range-parser

### ISSUE THREAD

**Issue by sachaw** [tinyhttp/tinyhttp#296]
The primary issue with this package is how it throws a TS1259 error how it's currently used.
I suggest deprecating it, as it appears to be unmaintained and has no inbuilt type definitions.
Using packages like this seems to go against the "0-legacy" aim of this package.

**Comment by talentlessguy** [comment]
do you know any good alternative to it?

also how does it throw an error? it's an internal dependency and shouldn't impact the end developer in any way in theory... maybe you have misconfigured typescript

**Comment by sachaw** [comment]
I have Typescript in strict mode, several of my dependencies require it, this is causing the error to be thrown.
As for alternatives, not aware of any sorry.

**Comment by talentlessguy** [comment]
@sachaw thanks for quick response, I'll try it out myself with a strict mode

the dumbest solution would be depending on @types/, otherwise idk

**Comment by sachaw** [comment]
omitting @types/range-parser throws a typedef not found like error, depending on it emits the aforementioned TS1259
