### ISSUE TITLE
Unhandled async errors

### ISSUE THREAD

**Issue by gabrielcursino** [tinyhttp/tinyhttp#297]
**Describe the bug**

Errors inside async functions are not handled by `onError`.

**To Reproduce**

```js
import { App } from '@tinyhttp/app';

const app = new App({
  onError: (err) => {
    console.log('Catch', err);
  }
});

app.use((_, res) => {
  throw 'Test';
});

app.listen(3000, () => console.log('Started on http://localhost:3000'));
```

Returns me on console: `Catch Test`

```js
import { App } from '@tinyhttp/app';

const app = new App({
  onError: (err) => {
    console.log('Catch', err);
  }
});

app.use(async (_, res) => {
  await new Promise(resolve => setTimeout(resolve, 500));
  throw 'Test';
});

app.listen(3000, () => console.log('Started on http://localhost:3000'));
```

Returns me on console: `(node:11384) UnhandledPromiseRejectionWarning: Test
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Expected behavior**

Handle sync and async errors

**Versions**

- `node`: 14.17.1
- `@tinyhttp/app`: 1.3.15

**Comment by talentlessguy** [comment]
Can't reproduce, works fine for me


![image](https://user-images.githubusercontent.com/35937217/127577457-3b1d07d6-631e-4691-acd4-a7f17784bbe5.png)

**Comment by gabrielcursino** [comment]
Sorry! I am using Typescript, and it was just a problem with output target.

Its working fine now!

**Comment by gabrielcursino** [comment]
Is there any way to subapps extend parent app options or parent app handle subapps errors?

Now, i am exporting parent options:

```js
...
export const options = {
  onError: (err: any, _: Request, res: Response) => {
    res.status(err.status ?? 500).json({ message: err?.message ?? 'Ocorreu um erro' });
  }
};
...
```

And importing it to use in subapps:

```js
import { app, options } from '../services/app';

const Controller = new App(options);
...
```

Is there a better way to do this or some way of parent app handle subapps errors?

**Comment by talentlessguy** [comment]
@gabrielcursino open a separate issue for that
