### ISSUE TITLE
Breaking change in @tinyhttp/app@1.3.14 w/ sirv middleware

### ISSUE THREAD

**Issue by pajasevi** [tinyhttp/tinyhttp#298]
**Describe the bug**

@tinyhttp/app has introduced an unknown bug in version 1.3.14 which breaks the app.

Bug presents itself when trying to access static files which are server via `sirv` middleware.

```js
this.app.use('/static', sirv('../static'));
```

Request fails and error passed to the general error handler consists only of `{ code: 404 }`.

This bug does not appear in any previous version of @tinyhttp/app or in any version of `sirv` middleware.

**To Reproduce**

1. install @tinyhttp/app@1.3.14
2. use `sirv` middleware to serve static files
3. start basic server
4. try to access those files (static HTML file for example)

**Expected behavior**

A static files will be served without an error

**Versions**

- `node`: 12.x.x
- `@tinyhttp/app`: 1.3.14
- `sirv`: 1.0.12

**Additional context**

Please maintain a proper changelog so your users are able to detect what are the changes in new releases and are able to guess which of these might break their application.

**Comment by talentlessguy** [comment]
does the bug occur in 1.3.13 and 1.3.15 versions?

**Comment by pajasevi** [comment]
@talentlessguy it DOES NOT occur in 1.3.13 and it OCCURS in 1.3.15

**Comment by talentlessguy** [comment]
@pajasevi ok so the bug starts to exist since 1.3.14

interesting

**Comment by pajasevi** [comment]
Yes, I have found this bug while upgrading from 1.3.3 to 1.3.15 and was able to pinpoint that it is a 1.3.14 version that breaks it.

**Comment by aral** [comment]
Possibly related to https://github.com/tinyhttp/tinyhttp/issues/301 ?

**Comment by pajasevi** [comment]
@talentlessguy any info on this?

**Comment by talentlessguy** [comment]
@pajasevi sorry I haven't looked into it yet

will do soon (I hope)

otherwise, if you do it faster than me, feel free to submit the PR

**Comment by talentlessguy** [comment]
@pajasevi  can you try to use absolute path? like `path.resolve(process.cwd(), 'static')`

**Comment by aldy505** [comment]
this is a working codesandbox: https://codesandbox.io/s/bold-torvalds-9k4ui?file=/src/index.js

if you still got a problem, let us know
