### ISSUE TITLE
Handle subapps errors on parent app

### ISSUE THREAD

**Issue by gabrielcursino** [tinyhttp/tinyhttp#299]
**Is your feature request related to a problem? Please describe.**
If an error occurs on subapp parent app `orError` is not called

**Describe the solution you'd like**
Handle subapps errors on parent app

**Describe alternatives you've considered**
As workaround i am exporting parent options:

```js
...
export const options = {
  onError: (err: any, _: Request, res: Response) => {
    res.status(err.status ?? 500).json({ message: err?.message ?? 'Ocorreu um erro' });
  }
};
...
```

And importing it to use in subapps:

```js
import { app, options } from '../services/app';

const Controller = new App(options);
...
```

Is there a better way to do this or some way of parent app handle subapps errors?

**Comment by talentlessguy** [comment]
Sorry I haven't been working on tinyhttp in some time, does express do the same with error handling?
