### ISSUE TITLE
Parameters are not url-decoded

### ISSUE THREAD

**Issue by fabiospampinato** [tinyhttp/tinyhttp#307]
**Describe the bug**

Parameters containing e.g. spaces must be url-encoded to be written in a URL, but when fetching those strings from tinyhttp I'd expect to get the original string back, I wouldn't expect the "%20" and stuff to make it through.

**To Reproduce**

1. Run the following:

```ts
import {App} from '@tinyhttp/app';

const app = new App ();

app.get ( '/:example', ( req, res ) => {

  res.send ( req.params.example );

});

app.listen ( 6789 );
```

2. Query the following:

```
http://localhost:6789/Foo%20Bar
```

3. See the following in the browser:

```
Foo%20Bar
```

Rather than "Foo Bar".

**Versions**

- `node`: 14.14.0
- `@tinyhttp/app`: 1.3.15

**Additional context**

I think parameters are url-decoded in Express.

**Comment by talentlessguy** [comment]
could you please try on Express as well just to confirm?

**Comment by fabiospampinato** [comment]
Sure, just checked with the following:

```js
const express = require ( 'express' );

const app = express ();

app.get ( '/:example', ( req, res ) => {

  res.send ( req.params.example );

});

app.listen ( 6789 );
```

<img width="1280" alt="Screen Shot 2021-08-28 at 23 59 04 (2)" src="https://user-images.githubusercontent.com/1812093/131232092-5cf1615e-ac9c-4701-9d8b-92a7eb876346.png">

**Comment by fabiospampinato** [comment]
Thanks <3
