### ISSUE TITLE
using path in content-disposition requires polyfill in the browser

### ISSUE THREAD

**Issue by CircleCode** [tinyhttp/tinyhttp#308]
content-disposition makes use of `import { basename } from 'path';`.

Since this is not available in browser, this requires a polyfill.

until webpack4, this polyfill was automatically added by webpack. Starting from webpack5, this is more prevalent since developer has to explicitely add the polyfill.
It would be nice to not rely on node specific apis, and to use only native browser features.

**Comment by talentlessguy** [comment]
tinyhttp isn't mean to be used in a browser :thinking:

**Comment by CircleCode** [comment]
thanks for the quick answer.
I was using your content-disposition since it is one of the more feature rich and light implementation.

Since you do not target the browser, feel free to close this issue; sorry for the noise :-)

**Comment by talentlessguy** [comment]
@CircleCode I don't know which stack you have but if you use Deno, you can import via `esm.sh/content-disposition` and it gets polyfilled automatically

**Comment by CircleCode** [comment]
I'm using webpack, and it is also possible to polyfill it.
But before polyfilling, I always look for a way to not requiring a polyfill :)

**Comment by talentlessguy** [comment]
if you're down, feel free to send a PR to use web APIs instead if Node built-ins

I'll most likely merge it if it passes tests and Node works with 12.4+

**Comment by CircleCode** [comment]
@talentlessguy Thanks for the fix (moreover since it is out of scope of your lib)
