### ISSUE TITLE
missing main field in package.json

### ISSUE THREAD

**Issue by CircleCode** [tinyhttp/tinyhttp#312]
your package seems to fail resolution with eslint because it lacks a main field in package.json.

For example, on `@tinyhttp/content-disposition`, `package.json` should include `"main": "./dist/index.js",`

without the `main` field, _normal imports_ do not work:

```ts
import { contentDisposition } from "@tinyhttp/content-disposition"; //eslint cannot find the module
```
but the following works:
```ts
import { contentDisposition } from "@tinyhttp/content-disposition/dist";
```

**Comment by CircleCode** [comment]
see import-js/eslint-plugin-import#2132 for eslint point of view:

> A package just for the browser still needs node behavior, even if that’s “nothing”, so having it lack a main is a bug.

**Comment by talentlessguy** [comment]
"main" field is for CommonJS

tinyhttp is ESM-only and uses "exports" instead.

so not planning on returning "main" back, it's an `eslint-plugin-import` issue not tinyhttp's, sorry :c

**Comment by CircleCode** [comment]
for future reference (I adhere to your point of view), there are issues on `eslint-plugin-import` to support `exports`:

- import-js/eslint-plugin-import#1810
- import-js/eslint-plugin-import#1868
