### ISSUE TITLE
Subapps not receiving params from parent apps

### ISSUE THREAD

**Issue by tbhmens** [tinyhttp/tinyhttp#314]
**Describe the bug**

A parent app that does ` app.use("/:path", subapp)`  doesn't pass req.params.path to the subapp.

**To Reproduce**

Code to reproduce the behavior:
```js
import { App } from "@tinyhttp/app";
const subapp = new App().get("/", (req, res) => {
  if (req.params.test == null) {
    res.send("req.params.test not passed");
  } else {
    res.send(`req.params.test passed: ${req.params.test}`);
  }
});
new App()
  .use("/:test", subapp)
  .listen(8080, () => console.log("listening on http://localhost:8080"));
```

**Expected behavior**

`req.params.test` is passed to the subapp

**Versions**

- `node`: 16.3.0
- `@tinyhttp/app`: 2.0.3

**Comment by talentlessguy** [comment]
wasn't it fixed before ?

https://github.com/tinyhttp/tinyhttp/issues/242

if it appeared again, can you tell please which version still works?

**Comment by tbhmens** [comment]
I thought so too, but looking at the test for 242, it looks like it didn't test if req.params got anything from the URL.

**Comment by talentlessguy** [comment]
@tbhmens got you, not cool then

any ideas on a possible fix?

**Comment by tbhmens** [comment]
I think I've found a solution by replacing 
https://github.com/tinyhttp/tinyhttp/blob/master/packages/app/src/app.ts#L321
with `req.params = { ...req.params, ...params }`, 
I'll make a PR in a sec 👍
