### ISSUE TITLE
Replace `req.connection` with `req.socket`

### ISSUE THREAD

**Issue by aldy505** [tinyhttp/tinyhttp#316]
Not really a bug or feature request per se, just a deprecation notice. Regarding these:

https://github.com/tinyhttp/tinyhttp/blob/94875e2c334c09143a849f529e028b7a6c22a18e/packages/app/src/request.ts#L16-L28

https://github.com/tinyhttp/tinyhttp/blob/94875e2c334c09143a849f529e028b7a6c22a18e/packages/app/src/request.ts#L33-L34

`req.connection` is deprecated. https://nodejs.org/api/http.html#http_request_connection

The solution for the first one is simple:

```ts
import { Socket } from 'net';

const trustRemoteAddress = ({ remoteAddress}: Pick<Socket, 'remoteAddress'>) => {
  // Or might be picked from IncomingMessage as well, so it'll be `req.socket.remoteAddress`
  const val = connection.remoteAddress
```

I haven't found the solution for the second one, and I don't have the time to work on this yet. So if anyone's up for this, they're absolutely welcome.

**Comment by diivi** [comment]
I tried working on the second one and found this https://nodejs.org/api/tls.html#tls_tlssocket_encrypted but the req.socket here is a normal net.Socket instance so I could'nt figure out how to use the tlsSocket.encrypted function
