### ISSUE TITLE
Shows `Cannot find module '@tinyhttp/app' from 'src/app.js'` error in jest with --experimental-vm-modules

### ISSUE THREAD

**Issue by Kamrulhasan12345** [tinyhttp/tinyhttp#319]
**Describe the bug**

Recently, while working with tinyhttp, everything works fine, the server also runs fine. But I am facing the issue with jest. 
I am running, `cross-env NODE_OPTIONS=--experimental-vm-modules yarn test` to test and finally it shows this: 
![image](https://user-images.githubusercontent.com/32530625/133911958-1cf8f9c9-3633-49e1-b0a1-8ba7f3d29625.png)

**To Reproduce**

1. Here is my repo: https://github.com/Kamrulhasan12345/tinyhttp-jest
2. run yarn install
3. then if windows then install cross-env and run `cross-env NODE_OPTIONS=--experimental-vm-modules yarn test` or else just `NODE_OPTIONS=--experimental-vm-modules yarn test`

**Expected behavior**

Test to run perfectly
**Versions**

- `node`: 16.6.1
- `@tinyhttp/app`: 2.0.4

**Additional**
I am posting this issue here, because it doesn't happen in any other modules except tinyhttp (also submodules)

**Comment by Kamrulhasan12345** [comment]
I went thoroughly in this issue. I tried making app.js -> app.mjs and remove type: module from package.json. Then installed esm module from npm, then used cjs imports and exprts everywhere except app.mjs. I imported app.mjs in server.js like this:
`const app = require('esm')(module)('./app.mjs')`. Then i ran `node src/server` and found this:
![image](https://user-images.githubusercontent.com/32530625/133932494-e3e52955-5344-433b-8bba-fe4e3a071347.png)
This almost same issue as in jest I guess.

**Comment by talentlessguy** [comment]
@Kamrulhasan12345 tinyhttp itself uses `enhanced-resolver` for tests

you could try passing a custom resolver to jest config and see if it works

**Comment by Kamrulhasan12345** [comment]
If I use the same resolver.cjs as tinyhttp has, then I get this error (in my main project):

![image](https://user-images.githubusercontent.com/32530625/133979507-6af758d2-14a5-4772-b09c-e93a1629564b.png)

I thought I must change the config, so I added `mainFields: ["module", "main"]` in resolver.cjs and then I am seeing this:

![image](https://user-images.githubusercontent.com/32530625/133979775-735c1b3a-dd98-4ce5-bf0d-393b4817e505.png)

I know that the issue is now solved for tinyhttp, but can you tell me what configs should I use for firebase in enhanced-resolve?

**Comment by talentlessguy** [comment]
@Kamrulhasan12345 I haven't ever used firebase so sorry but idk how to help :/

**Comment by Kamrulhasan12345** [comment]
ok, no problem

**Comment by Kamrulhasan12345** [comment]
I can try uvu (as seen in an issue in tinyhttp), that seems much easier!
