### ISSUE TITLE
Cookie parser request in typescript?

### ISSUE THREAD

**Issue by creepinson** [tinyhttp/tinyhttp#321]
**Describe the bug**

How can I use the cookie parser module with typescript? It shows this:
![image](https://user-images.githubusercontent.com/11761863/134441247-dee45ac2-e394-47d4-84b9-1f729f0b08c9.png)

> Type 'Request' is not assignable to type 'CookieParserRequest'.
        Property 'cookies' is optional in type 'Request' but required in type 'CookieParserRequest'.ts(2345)

I have also tried using
 ```ts
const app = new App<Record<string, unknown>>, CookieParserRequest, Response>();
```

**To Reproduce**

```ts
import { App } from "@tinyhttp/app";
import { cookieParser } from "@tinyhttp/cookie-parser";
const app = new App();

app.use(cookieParser()); // errors here

```

**Expected behavior**

No type errors in VSCode.

**Versions**

- `node`: 16.x
- `@tinyhttp/app`: 2.0.4

**Additional context**

I am using typescript 4.4.3 along with strict mode enabled with ESM and Node 16.

**Comment by creepinson** [comment]
I may have found a workaround but it's kind of ugly and annoying to use in every app.

```ts
import { App } from "@tinyhttp/app";
import { cookieParser, CookieParserRequest } from "@tinyhttp/cookie-parser";

app.use((req, res, next) =>
  cookieParser(process.env.SESSION_SECRET ?? "secret")(
    req as CookieParserRequest,
    res as unknown as globalThis.Response,
    next
  )
);
```

**Comment by talentlessguy** [comment]
try passing `CookieParserRequest` as a generic to `App`

although it's a type issue, cookie parser request also should have optional type, will fix asap

**Comment by talentlessguy** [comment]
@creepinson could you try now please? with latest th and cookie-parser
