### ISSUE TITLE
I get this error when using typescript example.

### ISSUE THREAD

**Issue by francelwebdev** [tinyhttp/tinyhttp#323]
francel@francel-Inspiron-N5010:~/Images/typescript$ npm start

> start
> node --experimental-loader ts-node/esm --experimental-specifier-resolution=node index.ts

(node:25298) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/modules/cjs/loader.js:889
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /home/francel/Images/typescript/node_modules/ts-node/dist/index.js
- /home/francel/Images/typescript/node_modules/ts-node/dist/esm.js
- /home/francel/Images/typescript/node_modules/ts-node/esm.mjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at loadCompiler (/home/francel/Images/typescript/node_modules/ts-node/dist/index.js:163:34)
    at create (/home/francel/Images/typescript/node_modules/ts-node/dist/index.js:170:28)
    at Object.register (/home/francel/Images/typescript/node_modules/ts-node/dist/index.js:139:21)
    at Object.registerAndCreateEsmHooks (/home/francel/Images/typescript/node_modules/ts-node/dist/esm.js:22:36)
    at file:///home/francel/Images/typescript/node_modules/ts-node/esm.mjs:11:9
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async internal/process/esm_loader.js:57:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/francel/Images/typescript/node_modules/ts-node/dist/index.js',
    '/home/francel/Images/typescript/node_modules/ts-node/dist/esm.js',
    '/home/francel/Images/typescript/node_modules/ts-node/esm.mjs'
  ]
}
francel@francel-Inspiron-N5010:~/Images/typescript$

**Comment by talentlessguy** [comment]
run `pnpm i typescript`

**Comment by francelwebdev** [comment]
ok, i must use pnpm? can't i use npm or yarn?

**Comment by francelwebdev** [comment]
I get this error after i use yarn add typescript.

francel@francel-Inspiron-N5010:~/Images/typescript$ npm start

> start
> node --experimental-loader ts-node/esm --experimental-specifier-resolution=node index.ts

(node:26233) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/home/francel/Images/typescript/node_modules/ts-node/src/index.ts:692
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:10:5 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.

10     console.log('Started on http://localhost:3000')
       ~~~~~~~

    at createTSError (/home/francel/Images/typescript/node_modules/ts-node/src/index.ts:692:12)
    at reportTSError (/home/francel/Images/typescript/node_modules/ts-node/src/index.ts:696:19)
    at getOutput (/home/francel/Images/typescript/node_modules/ts-node/src/index.ts:883:36)
    at Object.compile (/home/francel/Images/typescript/node_modules/ts-node/src/index.ts:1185:30)
    at /home/francel/Images/typescript/node_modules/ts-node/src/esm.ts:146:38
    at Generator.next (<anonymous>)
    at /home/francel/Images/typescript/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/francel/Images/typescript/node_modules/ts-node/dist/esm.js:4:12)
    at transformSource (/home/francel/Images/typescript/node_modules/ts-node/dist/esm.js:88:16) {
  diagnosticText: "\x1B[96mindex.ts\x1B[0m:\x1B[93m10\x1B[0m:\x1B[93m5\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2584: \x1B[0mCannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.\n" +
    '\n' +
    "\x1B[7m10\x1B[0m     console.log('Started on http://localhost:3000')\n" +
    '\x1B[7m  \x1B[0m \x1B[91m    ~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2584 ]
}

**Comment by talentlessguy** [comment]
looks like it asks you to add "dom" to `compilerOptions.lib`

**Comment by francelwebdev** [comment]
I now get this error.

francel@francel-Inspiron-N5010:~/Images/typescript$ npm start

> start
> node --experimental-loader ts-node/esm --experimental-specifier-resolution=node index.ts

(node:29604) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: exports is not defined in ES module scope
    at file:///home/francel/Images/typescript/index.ts:2:23
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by francelwebdev** [comment]
this is my package.json file.

{
  "name": "typescript",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node --experimental-loader ts-node/esm --experimental-specifier-resolution=node index.ts"
  },
  "dependencies": {
    "@tinyhttp/app": "2.0.5",
    "dom": "^0.0.3",
    "typescript": "^4.4.3"
  },
  "devDependencies": {
    "ts-node": "^10.2.1"
  }
}

**Comment by talentlessguy** [comment]
why did you instll `dom` as a dependency? also node 12.4+ is required

**Comment by francelwebdev** [comment]
i use latest node lts version.

**Comment by talentlessguy** [comment]
is the problem still happening?

**Comment by francelwebdev** [comment]
HI, yes i still have the problem, the solution i found is to use version 2.0.0. I cannot use the latest version.

**Comment by talentlessguy** [comment]
weird, not sure how to help

try each version since v2 to identify where it happens
