### ISSUE TITLE
2.x not working with typescipt

### ISSUE THREAD

**Issue by sachaw** [tinyhttp/tinyhttp#326]
**Describe the bug**

Using the latest 2.0 release with typescript, the following error is thrown:
```
CustomError: Cannot find package 'header-range-parser'
```
This is the case for node 16.9.1 and 16.10 relevant info: https://github.com/TypeStrong/ts-node/issues/1007

**To Reproduce**

1. Blank TS TinyHTTP app.
2. add `ts-node`: 16.10: `"ts-node": "github:TypeStrong/ts-node#pull/1457",` older versions: `"ts-node": "^10.2.1",`
3. in `package.json` set `"type": "module",`
4. set the start script to `"start": "node --loader ts-node/esm --experimental-specifier-resolution=node src/index.ts",`
5. example `tsconfig.json`
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "pretty": true,
    "module": "ESNext",
    "lib": ["ESNext"],
    "target": "ES5",
    "esModuleInterop": true,
    "moduleResolution": "Node",
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "skipLibCheck": true
  },
  "include": ["src/**/*"]
}
```

**Expected behavior**

Using the `--experimental-specifier-resolution=node` flag rewrites all my transpiled typescript files to append a `.js` extenstion on all file imports, however this won't work for `node_modules` 

Is there any workaround/way forward?

**Versions**

- `node`: 16.10
- `@tinyhttp/app`: 2.0.6

**Additional context**

**Comment by peschee** [comment]
The dependency `header-range-parser` is used in the `req` package:

https://github.com/tinyhttp/tinyhttp/blob/8643d6685c01520ca063c3f633b20767587818c0/packages/req/src/index.ts#L2

but it is not specified as a `dependency`, but only as a `devDependency`

**Comment by talentlessguy** [comment]
should be fixed now
