### ISSUE TITLE
Unpredictable output from `getQueryParams` 

### ISSUE THREAD

**Issue by groenroos** [tinyhttp/tinyhttp#330]
**Describe the bug**

If the `url` parameter given to `getQueryParams` does not contain query parameters, the method outputs an object with the full path as a key instead.

**To Reproduce**

```javascript
import { getQueryParams } from '@tinyhttp/url';

console.log(getQueryParams('/hello'));
console.log(getQueryParams('/hello?world=42'));
```

The above code yields:

```
{ '/hello': '' }
{ world: '42' }
```

**Expected behavior**

I would expect `getQueryParams` to yield an empty object for a `url` string that does not contain any query params.

```
{ }
{ world: '42' }
```

**Versions**

- `node`: 14.18.1
- `@tinyhttp/app`: 2.0.11

**Comment by shafa909** [comment]
Hey, am a new contributer , i would like to completed this task. i completed the steps until 'pnpm build'.
how i can run the file 'tinyhttp/tests/modules/url.test.ts' ?

**Comment by talentlessguy** [comment]
@shafa909 `pnpx jest 'tinyhttp/tests/modules/url.test.ts'`

**Comment by shafa909** [comment]
<img width="1305" alt="Screen Shot 2021-11-08 at 2 09 39 PM" src="https://user-images.githubusercontent.com/23289583/140710193-0adec4b1-9773-4b1b-97a3-63f7697e5a3f.png">
<img width="1305" alt="Screen Shot 2021-11-08 at 2 09 50 PM" src="https://user-images.githubusercontent.com/23289583/140710207-5f77018e-b9c5-44d0-aeab-caf4d364de3f.png">

**Comment by talentlessguy** [comment]
@shafa909 try running `pnpm i -r && pnpm build -r` and check if your Node.js version is `>=12.4`

**Comment by shafa909** [comment]
still showing same error ! :(

**Comment by SaiKiranMukka** [comment]
Hey @talentlessguy, can you assign this to me and review it?
