### ISSUE TITLE
Omitted optional param value is `"undefined"`

### ISSUE THREAD

**Issue by groenroos** [tinyhttp/tinyhttp#331]
**Describe the bug**

When an optional route param (i.e. `/foo/:bar?`) is not supplied for a particular request, the `req.params` object will still contain it, with a string value of `"undefined"`.

This would mean that i.e. `if (req.params.bar)` would unexpectedly always be truthy, even when the param was not supplied.

**To Reproduce**

Simple app with optional route param `bar`:

```js
import { App } from '@tinyhttp/app';
const app = new App();

app.get('/foo/:bar?', (req, res) => {
	console.log(req.params.bar);
	console.log(typeof req.params.bar);
});

app.listen(3000);
```

Visiting `http://localhost:3000/foo/bar` will correctly log:

```
bar
string
```

However, when you omit the param, `http://localhost:3000/foo` it will log:

```
undefined
string
```

**Expected behavior**

The value of the omitted param should not be a string of `"undefined"`. Instead, it should either be a literal `undefined` or `null` - or maybe the `bar` key should not be contained in `request.params` altogether.

**Versions**

- `node`: 14.18.1
- `@tinyhttp/app`: 2.0.11

**Comment by talentlessguy** [comment]
@juank1809 feel free to, instructions are in CONTRIBUTING.md

**Comment by Khotam** [comment]
hi @talentlessguy, can you assign me to this task?

**Comment by talentlessguy** [comment]
yeah no prob @Khotam
