### ISSUE TITLE
feature req - docs/demo of typescript project

### ISSUE THREAD

**Issue by robbiemu** [tinyhttp/tinyhttp#339]
**Is your feature request related to a problem? Please describe.**
It is pretty easy to get the hello world app running, but if you try unprepared to extend out from there on your own with typescript, it is possible that you will run into ERR_REQUIRE_ESM errors. Searching how to resolve this will produce suggestions like set `"type": "module",` in package.json or `esModuleInterop": true` in tsconfig compiler options, which presently will change the error to ERR_UNKNOWN_FILE_EXTENSION but will not resolve a starting config.

**Describe the solution you'd like**
A clear and concise description of known good settings with a npm package.json and tsconfig.

**Additional context**
https://stackoverflow.com/questions/70229544/ts-node-with-tinyhttp-is-not-compiling-properly

**Comment by talentlessguy** [comment]
check this out:

https://github.com/tinyhttp/tinyhttp/tree/master/examples/typescript
