### ISSUE TITLE
Cannot find module header-range-parser

### ISSUE THREAD

**Issue by SirReiva** [tinyhttp/tinyhttp#342]
**Describe the bug**

I cant init test example

**To Reproduce**

1. init npm with @tinyhttp/app dependecie and npm i
![image](https://user-images.githubusercontent.com/50754871/147473606-274580f1-14ae-426e-94b4-94f3fa4b1293.png)

2. index.js 
![image](https://user-images.githubusercontent.com/50754871/147473554-9c337989-e19e-49cd-90d0-c77b81c7a767.png)
3. node inde.js
 ![image](https://user-images.githubusercontent.com/50754871/147473419-cf31252b-516a-4576-8a4a-d838ad83457f.png)
**Expected behavior**

**Versions**

- `node`: 16.13.0
- `@tinyhttp/app`: 2.0.13

**Comment by kricha** [comment]
have same issue

**Comment by kricha** [comment]
because of https://github.com/r37r0m0d3l/header-range-parser/issues/66

**Comment by talentlessguy** [comment]
@kricha which version should we downgrade this dep to?

**Comment by SirReiva** [comment]
@talentlessguy with  "header-range-parser": "1.1.1" works, Its seems that last header-range-parser version is empty

**Comment by talentlessguy** [comment]
fixed

**Comment by r37r0m0d3l** [comment]
Somehow missed your issue. Fixed in new release 👉 https://github.com/r37r0m0d3l/header-range-parser/releases/tag/1.1.3.

**Comment by talentlessguy** [comment]
@r37r0m0d3l awesome thx, will bump the dep soon
