### ISSUE TITLE
No CommonJS output available

### ISSUE THREAD

**Issue by ankon** [tinyhttp/tinyhttp#343]
https://github.com/tinyhttp/tinyhttp/commit/4b010409e6f8272809fad08b8730f4bf333039aa dropped the CommonJS outputs (supposedly for good reasons!), but now the package description for at least `@tinyhttp/content-disposition` is off :)

![image](https://user-images.githubusercontent.com/1210641/149385275-6b905be0-2448-4696-b762-82f1280067c9.png)

**Comment by talentlessguy** [comment]
could you please PR with readme changes to remove the CJS part?

**Comment by ankon** [comment]
See #344.
