### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by hdemmer** [tinyhttp/tinyhttp#353]
I tried to swap in tinyhttp for my large-ish express application. Loved the initial experience, types, etc, but ultimately couldn't get it to run because it would have required ESM which I couldn't get to play nice with my ts-node-dev, esbuild, ... setup.

I'd love to use this lib, so I'm wondering what the rationale was behind dropping CommonJS, it's still somewhat widely used in the types of applications where you could have the most impact.

Consider this less of a direct feature request and more as feedback. Keep up the good work!

**Comment by talentlessguy** [comment]
it was answered before

CommonJS is a thing of the past. ESM is the future.
