### ISSUE TITLE
res.sendFile should respect content type when set

### ISSUE THREAD

**Issue by raymcdermott** [tinyhttp/tinyhttp#360]
**Is your feature request related to a problem? Please describe.**
res.sendFile does not get the content type correct 100% of the time and yet it does not respect content type when it is set on the response.

**Describe the solution you'd like**
res.sendFile should respect content type when it is set on the response.

**Describe alternatives you've considered**
I currently read the files locally and set the content. This is more code and I would rather not maintain it.

**Additional context**
Firefox gives XML errors when content types don't match its expectations - even if those expectations are wrong. It would be nice to be able to set the content-type as described here to avoid such noise.

https://stackoverflow.com/questions/51000009/i-keep-getting-this-error-xml-parsing-error-syntax-error-but-still-the-website

**Comment by talentlessguy** [comment]
Could you please submit a PR with the bug fix?

**Comment by rokaicker** [comment]
Hey @talentlessguy, if nobody is looking into this, is it okay if I give it a shot? 

But I am wondering, is it known under which circumstances it doesn't get the correct content-type? Ex. specific file types, etc.

**Comment by talentlessguy** [comment]
@rokaicker sure

I don't know myself but it needs checking
