### ISSUE TITLE
Failed to start https server

### ISSUE THREAD

**Issue by nbdomain** [tinyhttp/tinyhttp#376]
**Describe the bug**
import { App } from '@tinyhttp/app'
import fs from 'fs';
import http from 'http';
import https from 'https';
const app = new App()
var privateKey = fs.readFileSync(new URL('./127.0.0.1-key.pem', import.meta.url), 'utf8');
var certificate = fs.readFileSync(new URL('./127.0.0.1.pem', import.meta.url), 'utf8');
var credentials = { key: privateKey, cert: certificate };

var httpsServer = https.createServer(credentials, app); 
//generates Uncaught TypeError TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of App
 
**To Reproduce**

run above code

**Expected behavior**

no error

**Versions**

- `node`: 16
- `@tinyhttp/app`: 1.3.X

**Comment by talentlessguy** [comment]
For https server you should do this instead:

```js
const server = https.createServer(options)

server.on('request', app.attach).listen(3000)
```

See example [here](https://github.com/tinyhttp/tinyhttp/blob/master/examples/https/index.js)
