### ISSUE TITLE
Multiple path arguments (as array) to route

### ISSUE THREAD

**Issue by kevteljeur** [tinyhttp/tinyhttp#377]
**Is your feature request related to a problem? Please describe.**
Support for arrays of paths as the path argument to a route

**Describe the solution you'd like**
Currently only single paths are supported. ExpressJS supports arrays of paths to a route, so that multiple paths can resolve to the same route without needing each route to be specified separately.

**Describe alternatives you've considered**
The alternative is as now to create separate routes for each alternative path.

**Additional context**
```
app.get( [ '/child', '/other-child' ], ( req, res ) => {
	res.send( `${req.method || 'GET' } request to homepage` )
} )
```
vs 

```
app.get( '/child', ( req, res ) => {
	res.send( `${req.method || 'GET' } request to homepage` )
} )

app.get( '/other-child', ( req, res ) => {
	res.send( `${req.method || 'GET'} request to homepage` )
} )
```

**Comment by talentlessguy** [comment]
when I tried to implement it I had TS type conflicts, so PR with this feature is welcome

**Comment by jasonghent98** [comment]
Hi, is this issue still open and relevant? Would like to help resolve if so

**Comment by talentlessguy** [comment]
@jasonghent98 yes it's still relevant, a PR with this enhancement is very welcome

**Comment by kevteljeur** [comment]
Thank you!
