### ISSUE TITLE
Incompatible with Express middleware: `express.Handler`

### ISSUE THREAD

**Issue by sachaw** [tinyhttp/tinyhttp#387]
**Describe the bug**

I am attempting to use the `@bufbuild/connect-express` middleware.
The middleware has the following signature:
```ts
export declare function expressConnectMiddleware(options: ExpressConnectMiddlewareOptions): express.Handler;
```

**To Reproduce**

```ts
import { expressConnectMiddleware } from "@bufbuild/connect-express";
import { App } from "@tinyhttp/app";

const app = new App();

app
  .use(
    expressConnectMiddleware({
    }),
  )
```

**Versions**

- `node`: 20
- `@tinyhttp/app`: 2.0.32

**Comment by talentlessguy** [comment]
What exactly is not compatible? types or the API?

**Comment by sachaw** [comment]
Sorry. Types, API works flawlessly

**Comment by aarontravass** [comment]
How about piping it through instead? For reference, see Section **Middleware function validateCookies** in https://expressjs.com/en/guide/writing-middleware.html

**Comment by aarontravass** [comment]
Maybe extend it to use `express` as well? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts

**Comment by talentlessguy** [comment]
@aarontravass this will introduce an unecessary dependency, I think it's better to just align the types

@sachaw could you please attach a stack trace for the type error?

**Comment by sachaw** [comment]
```
Argument of type 'Handler' is not assignable to parameter of type 'App<any, Request, Response<any, any>> | RouterPathOrHandler<Request, Response<any, any>>'.
  Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type 'AsyncHandler<Request, Response<any, any>>'.
    Types of parameters 'req' and 'req' are incompatible.
      Type 'Request' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': header, accepted, param, host, baseUrl
```

Most pertinent bit I found: `RequestHandler` is not assignable to `AsyncHandler`

**Comment by talentlessguy** [comment]
@sachaw I see... I'll create issues to add those missing props from express request

**Comment by talentlessguy** [comment]
@sachaw `req.param` is deprecated in Express, but `req.baseUrl` should be added

also, is it possible to somehow pass a generic type for the middleware?

**Comment by aarontravass** [comment]
It seems like there's more than just that. I tried filling in whatever type mismatch it was throwing
```typescript
export interface Request extends IncomingMessage {
  originalUrl: string
  path: string
  url: string
  query: ParsedUrlQuery
  params: URLParams
  connection: Connection
  socket: TLSSocket | Socket
  route: Middleware //changed
  protocol: Protocol
  secure: boolean
  xhr: boolean
  hostname: string //changed
  ip: string //changed
  ips: string[] //changed
  subdomains: string[] //changed
  get(header: 'set-cookie'): string[] | undefined; //changed
  get(header: string): string | undefined; //changed
  range: (size: number, options?: Options) => any //changed
  accepts(): string[]; //changed
  accepts(type: string) : string //changed
  accepts(type: string[]) : string //changed
  accepts(...types: string[]) : string | string[] //changed
  acceptsCharsets(): string[]; //changed
  acceptsCharsets(charset: string): string | false; //changed
  acceptsCharsets(charset: string[]): string | false; //changed
  acceptsCharsets(...charset: string[]): string | false; //changed
  acceptsEncodings(): string[]; //changed
  acceptsEncodings(encoding: string): string | false; //changed
  acceptsEncodings(encoding: string[]): string | false; //changed
  acceptsEncodings(...encoding: string[]): string | false; //changed
  acceptsLanguages(): string[]; //changed
  acceptsLanguages(lang: string): string | false; //changed
  acceptsLanguages(lang: string[]): string | false; //changed
  acceptsLanguages(...lang: string[]): string | false; //changed

  is: (...types: string[]) => string | false //changed
  method: string //changed
  cookies: any //changed
  signedCookies: any //changed
  secret: string | string[] //changed
  fresh: boolean //changed
  stale: boolean //changed
  body: any
  app: App | any, //changed
  header(name: 'set-cookie'): string[] | undefined; //changed
  header(name: string): string | undefined; //changed
  param: any, //changed
  host: string, //changed
  baseUrl: string, //changed
  accepted: any //changed
}
```

In addition to that, it is now throwing another error
```log
Argument of type 'Handler' is not assignable to parameter of type 'App<any, Request, Response<any, any>> | RouterPathOrHandler<Request, Response<any, any>>'.
  Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type 'AsyncHandler<Request, Response<any, any>>'.
    Types of parameters 'res' and 'res' are incompatible.
      Type 'Response<any, any>' is missing the following properties from type 'Response<any, Record<string, any>, number>': sendfile, contentType, charsetts(2345)
```

**Comment by talentlessguy** [comment]
@aarontravass yeah response also has a few deprecated methods, I'm not sure what to do with that but I wouldn't want to implement them

**Comment by aarontravass** [comment]
It basically is asking for a copy of express's [`Request` type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5938bdc4182e810f7ef1bef39cd19c4c207b1421/types/express-serve-static-core/index.d.ts#L686). Should we extend it?

**Comment by aarontravass** [comment]
Function wise, it will break the code. For example, the current code supports `accepts: (...types: string[]) => AcceptsReturns` but the one in [express also supports taking argument as string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0a66a4616ebc4c3570d31be8b4071a5c30d22cb/types/express-serve-static-core/index.d.ts#L455), `accepts(type: string) : string`

**Comment by talentlessguy** [comment]
@aarontravass extending express types adds an extra dependency + it will not truthful as some functions are not implemented.

what about just using this?

```js
const app = new App<express.Request, express.Response>()
```

**Comment by aarontravass** [comment]
I just tried it and it seems to fail
```typescript
server.ts:5:30 - error TS2344: Type 'Response<any, Record<string, any>, number>' does not satisfy the constraint 'Request'.
  Type 'Response<any, Record<string, any>, number>' is missing the following properties from type 'Request': originalUrl, path, url, query, and 41 more.

5 const app = new App<Request, Response>()
                               ~~~~~~~~

server.ts:7:9 - error TS2345: Argument of type 'Handler' is not assignable to parameter of type 'App<any, Request, Response<any, any>> | RouterPathOrHandler<Response<...>, Response<...>>'.
  Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type 'AsyncHandler<Response<any, Record<string, any>, number>, Response<...>>'.
    Types of parameters 'req' and 'req' are incompatible.
      Type 'Response<any, Record<string, any>, number>' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': accepts, acceptsCharsets, acceptsEncodings, acceptsLanguages, and 56 more.

7 app.use(expressConnectMiddleware({}))
```

the code I used
```typescript
import { expressConnectMiddleware } from '@bufbuild/connect-express'
import { App } from './packages/app/src/index'
import { Request, Response } from 'express-serve-static-core'

const app = new App<Request, Response>()

app.use(expressConnectMiddleware({}))
```

**Comment by Ekott2006** [comment]
What's the next step???

**Comment by aarontravass** [comment]
Can you think of a way to extend current generics?

On Jun 8, 2023, at 1:51 PM, Ekott2006 ***@***.***> wrote:

﻿

What's the next step???

**Comment by Ekott2006** [comment]
This code will take time, there will be some kind of breaking changes, types or interfaces will have to conform a little to Express Standard but express doesn't need to be imported

**Comment by aarontravass** [comment]
Alright. Do you want this to be assigned to you?


On Jun 10, 2023, at 3:21 AM, Ekott2006 ***@***.***> wrote:

﻿

This code will take time, there will be some kind of breaking changes, types or interfaces will have to conform a little to Express Standard but express doesn't need to be imported

**Comment by Ekott2006** [comment]
No problem, am even on it right now. Now the implementation
Example:
TinyHTTP Example:
``` sendFile(path: string, options?: ReadStreamOptions, cb?: (err?: any) => void): Response<O, B> ```


In Express:
```  sendFile(path: string): void;
    sendFile(path: string, options: any): void;
    sendFile(path: string, fn: Errback): void;
    sendFile(path: string, options: any, fn: Errback): void;
    sendfile(path: string): void;
    sendfile(path: string, options: any): void;
    sendfile(path: string, fn: Errback): void; 
```

Will the other implementation be added??

Because I think that to fully support Express Middleware, We will have to cover Express.Handler(Express.Request and Express.Response) and more


e

**Comment by aarontravass** [comment]
That would mean changing a lot of code, as mentioned previously https://github.com/tinyhttp/tinyhttp/issues/387#issuecomment-1553601210 and https://github.com/tinyhttp/tinyhttp/issues/387#issuecomment-1553603425

**Comment by Ekott2006** [comment]
So what do you think should be done??

Should I change it??

**Comment by aarontravass** [comment]
Is there a way to use generics? Consider the example of `app.use`
The first argument can be
1. Another app 
```ts
const app = new App();
const subapp = new App();
app.use(subapp)
```
2. A path or array of paths
```ts
app.use('/route', subapp)
app.use(['/route1', '/route2'], subapp)
```
3. Array of wares
```ts
app.use([ware1(req, res), ware2(req, res)])
```

But the type of arg in `.use` is `UseMethodParams<Req, Res, App>`. See https://github.com/tinyhttp/tinyhttp/blob/c5d4a90b3c2cf8ded8c5c1f281dd719ebf8cfcc5/packages/app/src/app.ts#L191

The fn is not overloaded.

**Comment by Ekott2006** [comment]
Okay, but do you think it will fix the Express middleware issue Problem??

```
const app = new App();
const subapp = new App();
app.use(subapp)
```

What will be like a use case to attach an app as a middleware. The rest looks good to me

**Comment by aarontravass** [comment]
>Okay, but do you think it will fix the Express middleware issue Problem??
>What will be like a use case to attach an app as a middleware. The rest looks good to me

My above comment was an example of how using generic types, a function could be 'pseudo' overloaded. You'll have to figure out something similar i.e. create a generic type that can be a type for the argument passed without overloading the function. Does that help clarify?

**Comment by Ekott2006** [comment]
If you just create a generic and it works(ts will most likely not allow it). But what if a middleware  calls an express Handler function or methos that we doesn't implement here it can lead to unknown bugs in the error

**Comment by aarontravass** [comment]
Sorry for the late reply. I reckon most handlers can be passed via a function. For example, `.use` can take the `req` and `res` in a function as argument and can then be passed to the handlers. 
@talentlessguy what do you think?

**Comment by talentlessguy** [comment]
I think the solution would be to introduce overloading to `use` method (and others) to individually overload specific routes.

It should make it easier to change the request / response types in invididual places while not enforcing it on the whole app.

And I'll make a separate issue to implement missing signatures for some methods to increase type compat

**Comment by talentlessguy** [comment]
I've looked into it - You should use `@connectrpc/connect-node` instead. Type-wise middleware using express types won't be supported because they require implementing deprecated methods
