### ISSUE TITLE
Exporting a router file is not working

### ISSUE THREAD

**Issue by phtdacosta** [tinyhttp/tinyhttp#402]
**Describe the bug**

```
TypeError: h is not a function
    at file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:143:7
    at file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:317:34
    at loop (file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:320:81)
    at next (file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:321:66)
    at C:\Users\user\Desktop\project\api\node_modules\.pnpm\sirv@2.0.3\node_modules\sirv\build.js:180:28
    at file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:143:7
    at file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:317:34
    at loop (file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:320:81)
    at next (file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+app@2.1.0/node_modules/@tinyhttp/app/dist/index.js:321:66)
    at file:///C:/Users/user/Desktop/project/api/node_modules/.pnpm/@tinyhttp+cors@2.0.0/node_modules/@tinyhttp/cors/dist/index.js:58:57
```

This happens whenever I make a request to the API, after I put all routes from a controller in a routes file that looks like that

```
import { Router } from "@tinyhttp/router"

import {
	authUser
} from "./controllers/authController.js"

const router = new Router()

router.post("/auth", authUser)

export default router
```

to the main file of the API, where I integrate it in the app object using ```.use("/user", authRoutes)```

**Expected behavior**

I think that what was expected to happen is that it would just work, right.

**Versions**

- `node`: 16.16
- `@tinyhttp/app`: 2.1.4

**Comment by aarontravass** [comment]
Hi there. Thanks for posting the issue. Could you please post the import and subsequent use of `authRoutes`?

**Comment by phtdacosta** [comment]
The ```authRoutes``` is literally the imported router file which I described its contents, so I import it like usual, ```import router as authRoutes from "./authRoutes.js"```

**Comment by aarontravass** [comment]
> The `authRoutes` is literally the imported router file which I described its contents, so I import it like usual, `import router as authRoutes from "./authRoutes.js"`

@talentlessguy, replied to a similar issue. See https://github.com/tinyhttp/tinyhttp/issues/400#issuecomment-1676349636

**Comment by aarontravass** [comment]
In summary, `@tinyhttp/router` is more like an internal package. You should use subapps. For example
```ts
import { App } from "@tinyhttp/app"

const subApp = new App()
const app = new App()

subApp.post("/auth", handler)

app.use(subApp)

```

**Comment by phtdacosta** [comment]
Thanks so much @aarontravass! I see.

Was it designed to be that way? What would be the advantages of using this style of "subapps" over creating Router objects and integrating(.use) them in the main app, like I did?

**Comment by aarontravass** [comment]
> Was it designed to be that way?

Yes, I believe so.
<hr>

> What would be the advantages of using this style of "subapps" over creating Router objects and integrating(.use) them in the main app, like I did?

The router is just a bare-bones module and by itself has little to no use. Subapps are regular apps which can be nested and hence you have full control of each nested app which makes them way more powerful. This control is in the form of options/settings. The following are the ones you can set

https://github.com/tinyhttp/tinyhttp/blob/bec8ee50024a645ad26663752b5761dd03508576/packages/app/src/app.ts#L35-L42

In contrast, the router gives no such flexibility.

<hr>

> Also, what is the point of @tinyhttp/router then?

The router just holds the middleware. Each handler or subapp you pass becomes the middleware for the main app/sub app and this is held in the router.

<hr>

> What would be the use case for this feature?

I am not sure about this. 

<hr>

> Adding a few more context to this internal package on its README page would probably help others in the future who would end up in the same situation as me or this person who you mentioned.

Yes, I think this would be a good idea.

<br>
Hope this helps.

**Comment by talentlessguy** [comment]
As was mentioned before, `@tinyhttp/router` is an internal package. I'm sorry for confusion, I'll add a "this is an internal package and is not meant to be used directly" to README.

Router's purpose is to move off middleware management to a separate utility class, router. You can't use it together with App unless you do some customization on top of it.
