### ISSUE TITLE
Create a community server

### ISSUE THREAD

**Issue by phtdacosta** [tinyhttp/tinyhttp#403]
Given similar & recent JS projects like Hono.js, Bun.js and even React.js all got a Discord server and it leverages the communication and community-building around the initiative, it would be great if someone from the tinyhttp staff could start one, the upkeep is low and the advantages are incredible. I really like tinyhttp, I use it on my company and I hope the project only grows! I could help setup the group too, if you need.

**Comment by talentlessguy** [comment]
or maybe Matrix / some decentralized alternative

**Comment by aarontravass** [comment]
gitter is pretty popular I guess https://gitter.im/

**Comment by aldy505** [comment]
+1 for Gitter. Until now, I still don't know who actually uses Tinyhttp on production. We can acquire lot of feedbacks from there.

**Comment by talentlessguy** [comment]
alright, I'll setup a Gitter server (or any other Matrix server) within this week

**Comment by talentlessguy** [comment]
I've created https://tinyhttp.zulipchat.com, going to add the link to the website

**Comment by aldy505** [comment]
@talentlessguy it says "You need an invitation to join this organization.". Shouldn't this be made public without invitation? I don't know how Zulip works, though.

**Comment by talentlessguy** [comment]
> @talentlessguy it says "You need an invitation to join this organization.". Shouldn't this be made public without invitation? I don't know how Zulip works, though.

oops, fixed now
