### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by MRakox** [tinyhttp/tinyhttp#404]
![image](https://github.com/tinyhttp/tinyhttp/assets/52240615/df3db635-c83b-4a63-ba56-6976e879472e)

**Comment by talentlessguy** [comment]
for whatever reason it shut down itself... it's back up now, thanks for reporting

**Comment by MRakox** [comment]
Thank you for your time!

**Comment by MRakox** [comment]
Still doesn't working for me :(

**Comment by talentlessguy** [comment]
ok i know what I'll do I'll just deploy it on some service instead of hosting it on VPS

it keeps crashing for whatever reason :(

please wait a little till I re-deploy it elsewhere

**Comment by MRakox** [comment]
Thank you soooo much!!

**Comment by talentlessguy** [comment]
it's deployed on Render now, if it crashes I'll see logs immediately

**Comment by MRakox** [comment]
TYSM ♥️
I can now beggins building my tiny app :)

**Comment by MRakox** [comment]
> it's deployed on Render now, if it crashes I'll see logs immediately

sorry it's down again...
