### ISSUE TITLE
Predefined error type

### ISSUE THREAD

**Issue by lanwin** [tinyhttp/tinyhttp#415]
**Is your feature request related to a problem? Please describe.**
I noticed that there is code to raise an Error with an code property. But it would be nice to have a pre defined error type to raise http status codes as an error.

```
import { HttpStatusError } from '@tinyhttp/app'

app.get('/', await (req, res) => {
  throw new HttpStatusError(404,"Its not found");
});
```

**Comment by aarontravass** [comment]
Do you mean something like what Nestjs does? 

https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/packages/common/exceptions/forbidden.exception.ts#L11

**Comment by lanwin** [comment]
Yes but not that complicated. They seem to have an error for each status code. I would suggest to go with just one extra class HttpStatusError(int code, string message);

**Comment by talentlessguy** [comment]
IMO this should be handled via `res.sendStatus` instead of throwing. Introducing a custom error class seems redundant.

**Comment by lanwin** [comment]
Yes that would be an alternate to setting the status. The error helps in complex workflow since it it also stops execution and communicating the error upwards the callstack. This way it prevents c++ like error handling code in some cases.
