### ISSUE TITLE
ZOD support / example

### ISSUE THREAD

**Issue by lanwin** [tinyhttp/tinyhttp#416]
**Is your feature request related to a problem? Please describe.**
I made good experience with ZOD for validating query, from, body parameters. It would be awesome if tinyhttp would have a lightweight support for using it. 

I have something like this in mind:

```typescript
import { validate } from '@tinyhttp/zod'

const userSchema = z.object({
  name: z.string(),  
});

app.get('/user', (req, res) => {
    const user = validate.query(req, userSchema); // throw an bad request error when validation fails. 
    ....
`);
```

**Comment by lanwin** [comment]
The problem here is that this would throw an error if schema validation fail. With would result into an 500er. 

To mitigate that I would need to add an try catch to every handler with res.status(400).send("validation failed"). That would be pretty verbose. Or add an general handler that catches the zod error and returns bad request. But that code must also be copy and pasted to each project you would want to use. 

But even with that, the context gets lost. We have an zod validation error and did not know where it come from. Did the error was userSchema.parse(req.query) or userSchema.parse(req.body).....

With `validate.query(req, userSchema)` we have the context and can raise a proper error. 400 query parameters arent valid....

**Comment by aarontravass** [comment]
I understand. Thank you for the explanation. My only gripe is that this would not be validation agnostic but in hindsight it's ok since nestjs also uses class validator in their docs.

@talentlessguy what do you think?

**Comment by talentlessguy** [comment]
is there something similar for other web framework?

Implementing a custom middleware should be fairly straightforward

**Comment by lanwin** [comment]
Well, if you develop an web application with typescript you always have do deal with the problem that input parameters and form parameters are untyped strings. You always have to write code to convert them to an typed object. Even in simple cases like simple paramters like number page and number size. 

The most other frameworks give you a simple object with properties of type string and I have written a lot code that handles the conversion to proper types in the past. 

So from my perspective a web framework with first class typescript support, should offer a build in way to deal with that kind of problems.

**Comment by talentlessguy** [comment]
fair points but I think a user owned package would be sufficient. There are other validator libraries and integrating and keeping up with each single library is a lot of labor.

I'm not opposed to adding a link to any tinyhttp-focused validator libraries to the website and docs.
