### ISSUE TITLE
[docs] outdated app.engine example with eta

### ISSUE THREAD

**Issue by typicode** [tinyhttp/tinyhttp#422]
Hello :wave: doc example may be outdated.

**Describe the bug**

Eta doesn't support app.engine() anymore.

https://tinyhttp.v1rtl.site/docs/main-concepts.html#template-engines

> Eta no longer supports the Express.js app.engine() function, but it's still completely possible to use with Express.js!

https://eta.js.org/docs/resources/express

https://github.com/search?q=repo%3Aeta-dev%2Feta%20renderFile&type=code `renderFile` is not found in the codebase.

**Comment by talentlessguy** [comment]
Hey, I think I need to mention in the docs that it's Eta V2.

from what I know Eta V3 does all the engine stuff on its own.
