### ISSUE TITLE
`req.hostname` does not include port when applicable

### ISSUE THREAD

**Issue by Lordfirespeed** [tinyhttp/tinyhttp#436]
**Describe the bug**

**To Reproduce**

```ts
import { App } from "@tinyhttp/app"

const app = new App({
  settings: {
    networkExtensions: true,
  },
})

app.use("/", (req, res) => {
  res.send(`Hostname: ${req.hostname}`)
})

app.listen(3000)
```

`curl localhost:3000`

**Actual behaviour**
- Response `Hostname: localhost`

**Expected behavior**
- Response `Hostname: localhost:3000`

**Versions**

- `node`: 21
- `@tinyhttp/app`: 2.3.1

**Comment by aarontravass** [comment]
This behavior is shown by express as well.

```js
import express from "express";

const app = express();

app.get('/foo',(req, res) => void res.send(req.hostname))

app.listen(3000);

```

Not really a bug.

**Comment by aarontravass** [comment]
Here's another helpful answer
https://serverfault.com/questions/953380/when-specifying-a-host-name-do-we-still-need-to-specify-a-port

**Comment by aarontravass** [comment]
And here's the spec https://www.w3.org/Addressing/HTTPAddressing.html

**Comment by Lordfirespeed** [comment]
My bad, you're right. 

Closing this - will open a feature request instead
