### ISSUE TITLE
More network extensions

### ISSUE THREAD

**Issue by Lordfirespeed** [tinyhttp/tinyhttp#437]
When using a trusted reverse proxy, it can be tricky to identify the request port.

For example:
- user requests `https://foo.com:8901`
- reverse proxy server forwards request to `localhost:3000` and attaches `X-Forwarded-Host` header with value `foo.com:8901`
- `req.hostname` reads `foo.com` 
- identifying the request port is contrived (involves reading `X-Forwarded-Host` header **only when the proxy is trusted**) although the framework has already done the required processing

Proposal:
- add `request.port` network extension (self-explanatory, e.g. `8901`)
- add `request.host` network extension (combination of hostname and port, e.g. `foo.com:8901`)
- add `request.origin` network extension (combination of protocol, hostname and port, e.g.`https://foo.com:8901`
- add `request.href` network extension (combination of origin and path, e.g. `https://foo.com:8901/path` 

To match the [Node.js URL API](https://nodejs.org/api/url.html).

**Comment by Lordfirespeed** [comment]
Related: #436

@aarontravass thoughts?

**Comment by aarontravass** [comment]
> Related: #436
> 
> @aarontravass thoughts?

For whatever reason, express does not have these properties as part of the incoming http request. Nevertheless, I don't mind having these in th.

**Comment by talentlessguy** [comment]
Request is not a URL, but you can construct a URL from a request path. I don't think its necessary to pollute request object when you can write a simple middleware to add this URL object 

I'd abstain from adding anything new, the target goal of tinyhttp is as little changes as possible and as much compat with express as possible, while staying faster

**Comment by talentlessguy** [comment]
sorry my bad, it was req.protocol and req.hostname

we can add req.port

**Comment by Lordfirespeed** [comment]
> we can add req.port

The others could be added to the request prototype as getter functions, which would not incur any additional memory/processing costs unless accessed.

**Comment by talentlessguy** [comment]
I don't think there's a need for new listen arguments, we already have app settings with networkExtensions

**Comment by Lordfirespeed** [comment]
I'm referring to the options [here](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener) which tinyhttp consumers cannot specify unless they invoke `createServer` themselves

**Comment by aarontravass** [comment]
I am unsure if those options are truly required. See Express 5.x - API Reference (expressjs.com)<https://expressjs.com/en/5x/api.html#app.listen>

________________________________

**Comment by Lordfirespeed** [comment]
> I am unsure if those options are truly required.

If your point is 'we support it by allowing people to call `createServer` themselves, sure 👍🏼
