### ISSUE TITLE
Support for url forwarding

### ISSUE THREAD

**Issue by aweigor** [tinyhttp/tinyhttp#440]
Making changes to the `req.url` from inside of middleware does not affect the execution order.

Suppose such an example:
```
const app = new App()
const rewrite = (req, res, next) => {
  req.url = '/b'
  next()
}

app.use(rewrite).use('/a', (req, res) => {
  res.send({
    url: req.originalUrl
  })
}

app.listen(3000)
```

Actual output for `/a` is `{ url: '/b }`, while expected output is `{ url: '/a }` since the middleware was binded to the route `/a`.

It would be great if user could be redirected to the corresponding route by making changes in `req.url`.

**Comment by aarontravass** [comment]
Hello @aweigor, thank you for raising this issue. When I ran the above code in express, it gave me 404 as the output
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /a</pre>
</body>
</html>
```

Since we are replicating the behavior of express, it would better to return 404 instead of a 200 response

**Comment by aarontravass** [comment]
Also, the output I got for your code was
```json
{
  "url": "/a"
}
```

Maybe your package version is outdated?

**Comment by aweigor** [comment]
Hello @aarontravass! Yes, if we'll define mw on route `/b` in express, the request will fall into it, otherwise 404 will be expected. For example:

```
const app = new express();
const rewrite = (req, res, next) => {
	req.url = "/b";
	next();
};

app.use(rewrite).use("/a", (req, res) => {
	res.send('Hello from a');
});

app.use(rewrite).use("/b", (req, res) => {
	res.send('Hello from b');
});

app.listen(3000);
``` 

You were right about my test package, now th responses with `\a`. Anyway, forwarding would be more preferable, i think.

**Comment by aarontravass** [comment]
> forwarding would be more preferable, i think

I'm not sure. tinyhttp is supposed to be a drop in replacement and if an existing user is reliant on express's feature of returning 404 and now after replacing it with tinyhttp, they see a different behavior, it might be cause for concern.

**Comment by aweigor** [comment]
Agree, that is exactly why we need forwarding. I suppose returning 404 is not quite the feature. It returns 404 because rewriting req.url to `\b` forwards to undefined route `/b` in the topic example. Please check express behavior with the same test but route `/a` replaced by `/b`.

```
const app = new App()
const rewrite = (req, res, next) => {
  req.url = '/b'
  next()
}

app.use(rewrite).use('/b', (req, res) => {
  res.send({
    url: req.originalUrl
  })
}

app.listen(3000)
```
Listen http://localhost:3000/a. By the way, now th will return 404.

**Comment by aweigor** [comment]
I already have an implementation in which th behaves as express including 404 feature. https://github.com/aweigor/tinyhttp, `url-rewrite` branch.

**Comment by aarontravass** [comment]
> I already have an implementation in which th behaves as express including 404 feature. https://github.com/aweigor/tinyhttp, `url-rewrite` branch.

Thank you! Can you raise a pull request so that we can review it?

**Comment by talentlessguy** [comment]
Why would you forward like this instead of 30X redirects? Its built-in into HTTP standard. tinyhttp exposes it via `res.redirect`

**Comment by aweigor** [comment]
@talentlessguy, aloha.

Some projects requires rewrite module to make specific server-side actions, such as redirection without changes in browser url. In particular this is necessary when making human-readable urls. While digging about Middlewares, I found comprehensive explanation on rewrite and redirect cases in ASP.NET documentation.

According to https://expressjs.com/en/guide/using-middleware.html:
...
Middleware functions can perform the following tasks:
- Execute any code.
- **Make changes to the request and the response objects.**
- End the request-response cycle.
- Call the next middleware function in the stack.

Some projects that used express's https://www.npmjs.com/package/express-urlrewrite module lost their rewrite functionality after switching to th, see https://github.com/typicode/json-server/issues/1512.

Therefore to solve these issues I want to add the correct req.url rewriting behavior and make a url-rewrite module for the th.

**Comment by talentlessguy** [comment]
I see, this makes sense to me now
